<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="47808" started-at="2017-10-20T12:35:11Z" finished-at="2017-10-20T12:35:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="47808" started-at="2017-10-20T12:35:11Z" finished-at="2017-10-20T12:35:58Z">
      <class name="com.usgbc.dev.regression.StoreTest">
        <test-method status="PASS" signature="getDriver()[pri:0, instance:com.usgbc.dev.regression.StoreTest@6a4f787b]" name="getDriver" is-config="true" duration-ms="6912" started-at="2017-10-20T18:05:11Z" finished-at="2017-10-20T18:05:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDriver -->
        <test-method status="FAIL" signature="testStore()[pri:0, instance:com.usgbc.dev.regression.StoreTest@6a4f787b]" name="testStore" duration-ms="39319" started-at="2017-10-20T18:05:17Z" finished-at="2017-10-20T18:05:57Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[expected [https://test-dynamic-usgbc.pantheonsite.io/store/contact] but found [http://test-dynamic-usgbc.pantheonsite.io/store/contact]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: expected [https://test-dynamic-usgbc.pantheonsite.io/store/contact] but found [http://test-dynamic-usgbc.pantheonsite.io/store/contact]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.usgbc.dev.business.Store.StoreModule(Store.java:34)
	at com.usgbc.dev.regression.StoreTest.testStore(StoreTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStore -->
        <test-method status="PASS" signature="closeDriver(org.testng.ITestResult)[pri:0, instance:com.usgbc.dev.regression.StoreTest@6a4f787b]" name="closeDriver" is-config="true" duration-ms="1559" started-at="2017-10-20T18:05:57Z" finished-at="2017-10-20T18:05:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testStore status=FAILURE method=StoreTest.testStore()[pri:0, instance:com.usgbc.dev.regression.StoreTest@6a4f787b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- com.usgbc.dev.regression.StoreTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
